### ISSUE TITLE
Node-bourbon does not work with scss

### ISSUE THREAD

**Issue by Shmasya** [lacroixdesign/node-bourbon#28] opened 2016-03-19 10:03 UTC
Prompt please why does not work with scss. In the file main.I write scss @import 'bourbon'; and in the file gulp.js I write includePaths: require('node-bourbon').includePaths section .pipe(sass({...}))

**Comment by iamlacroix** [comment] 2016-03-19 18:20
Likely a duplicate of #27. We just released v4.2.7, does the issue persist with that version too?

**Closed by iamlacroix** 2016-03-19 18:20 UTC

**Comment by Shmasya** [comment] 2016-03-19 18:30
Yes, The error is identical.

**Comment by iamlacroix** [comment] 2016-03-19 18:37
Well what errors are you receiving? "Does not work" is unfortunately very hard to debug. Is the source available in a repo available on GitHub so that we can try to duplicate your issue?

**Comment by Shmasya** [comment] 2016-03-19 18:58
It's my package.js

{
  "name": "gulp-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Shmasya",
  "license": "ISC",
  "devDependencies": {
    "browser-sync": "^2.11.1",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-concat": "^2.6.0",
    "gulp-minify-css": "^1.2.4",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.2.0",
    "gulp-uglifyjs": "^0.6.2",
    "node-bourbon": "^4.2.7"
  }
}

It's my gulpfile.js
gulp.task('styles', function () {
	return gulp.src('scss/*.scss')
	.pipe(sass({
		includePaths: require("bourbon").includePaths
	}).on('error', sass.logError))
	.pipe(rename({suffix: '.min', prefix : ''}))
	.pipe(autoprefixer({browsers: ['last 15 versions'], cascade: false}))
	.pipe(minifycss())
	.pipe(gulp.dest('app/css'))
	.pipe(browserSync.stream());
});

**Comment by iamlacroix** [comment] 2016-03-19 19:01
Thanks for posting that. What error(s) are you receiving?

**Comment by Shmasya** [comment] 2016-03-19 19:03
http://i.imgur.com/AXwL9k5.png

**Comment by iamlacroix** [comment] 2016-03-19 19:12
Just set it up locally and it imported Bourbon & compiled without issue, so it doesn't appear to be an issue with your configuration. Your error message looks to be caused by the `scss/fonts.css` file. What are the contents of that file?

**Comment by Shmasya** [comment] 2016-03-19 19:13
It's content of fonts.scss file http://i.imgur.com/wktslnp.png

**Comment by iamlacroix** [comment] 2016-03-19 19:15
Strange, that's all I had in my file I created to test it for you. Can you try nuking your `node_modules` folder and then run `npm install` again?

**Comment by Shmasya** [comment] 2016-03-19 19:22
Yes, a try npm install, but still not

**Comment by iamlacroix** [comment] 2016-03-19 19:50
Hmm, very strange. Can you provide the contents of your `node_modules/node-bourbon/index.js`?

**Comment by Shmasya** [comment] 2016-03-19 19:53
```var path = require('path');
var bourbon = require('bourbon');

module.exports = {

  includePaths: [bourbon.includePaths],

  with: function() {
    var paths  = Array.prototype.slice.call(arguments);
    return [].concat.apply([bourbon.includePaths], paths);
  }

};```

**Comment by iamlacroix** [comment] 2016-03-19 20:31
So weird. Unfortunately I can't seem to reproduce it with the code provided so far, so I'm not sure how else to proceed at this point. I wish I could be more help.

**Comment by Shmasya** [comment] 2016-03-19 20:34
Do you all work? How can I specify the path by force?

**Comment by iamlacroix** [comment] 2016-03-21 19:11
Just pushed v4.2.8 which fixes a different issue. Hopefully this resolves your issue too.
