### ISSUE TITLE
please update bourbon version 4.2.2

### ISSUE THREAD

**Issue by choiks14** [lacroixdesign/node-bourbon#19] opened 2015-04-23 02:59 UTC
please update bourbon version 4.2.2

**Comment by iamlacroix** [comment] 2015-04-30 18:11
Duplicate of #18. Resolved in release [v4.2.2](https://github.com/lacroixdesign/node-bourbon/releases/tag/v4.2.2)

**Closed by iamlacroix** 2015-04-30 18:11 UTC
